schema: schema.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    "Default Grapgql Endpoint":
      url: "http://localhost:3000/graphql"
      headers:
        "user-agent": "JS GraphQL"
      introspect: false